# Generated by Django 4.0.4 on 2023-08-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('driver_id', models.IntegerField()),
                ('status', models.CharField(choices=[('working', 'Working'), ('resting', 'Resting'), ('off', 'Off')], max_length=50)),
            ],
        ),
    ]
